version: "3.8"
services:
  web-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: stunning-memory-wip
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: daitya96/stunning-memory-golang:latest
    container_name: stunning-memory
    ports:
      - 3000:3000
