apiVersion: v1
kind: Service
metadata:
  name: {{ include "stunning-memory.name" . }}-svc-clusterip
  labels:
    {{- include "stunning-memory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stunning-memory.selectorLabels" . | nindent 4 }}
